version: '3.8'
services:
  dcs-postgres:
    image: bitnami/postgresql:latest
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: passwd
      POSTGRESQL_DATABASE: fast_delivery_app
    ports:
      - 5432:5432
    volumes:
      - ./src/infra/database/data/postgres:/var/lib/postgresql/data
